version: '3.1'
services:
  website:
    container_name: website
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - /home/vagrant/student-list/website:/var/www/html
  api:
    container_name: api
    image: simple_api:v1
    volumes:
      - /home/vagrant/student-list/simple_api:/data
    ports:
      - "5000:5000"
#volumes:
#  website: